#ifndef __COLORS_HPP__
# define __COLORS_HPP__

#define BOLD "\e[1m"

#define COLOR(x) "\e[0;38;5;" #x "m"
#define BOLD_COLOR(x) "\e[1;38;5;" #x "m"

#define BABY_BLUE COLOR(117)
#define BABY_PINK COLOR(176)
#define CONST_BLUE COLOR(33)
#define CLASS_GREEN COLOR(42)
#define FAINT_GRAY COLOR(236)

#define BOLD_BABY_BLUE BOLD_COLOR(117)
#define BOLD_BABY_PINK BOLD_COLOR(176)
#define BOLD_CONST_BLUE BOLD_COLOR(33)
#define BOLD_CLASS_GREEN BOLD_COLOR(42)
#define BOLD_FAINT_GRAY BOLD_COLOR(236)

#define SIMPLE_COLOR(x) "\e[" #x "m"
#define BOLD_SIMPLE_COLOR(x) "\e[1;" #x "m"

#define RED SIMPLE_COLOR(31)
#define GREEN SIMPLE_COLOR(32)
#define YELLOW SIMPLE_COLOR(33)
#define BLUE SIMPLE_COLOR(34)
#define MAGENTA SIMPLE_COLOR(35)
#define CYAN SIMPLE_COLOR(36)
#define WHITE SIMPLE_COLOR(37)

#define BOLD_RED BOLD_SIMPLE_COLOR(31)
#define BOLD_GREEN BOLD_SIMPLE_COLOR(32)
#define BOLD_YELLOW BOLD_SIMPLE_COLOR(33)
#define BOLD_BLUE BOLD_SIMPLE_COLOR(34)
#define BOLD_MAGENTA BOLD_SIMPLE_COLOR(35)
#define BOLD_CYAN BOLD_SIMPLE_COLOR(36)
#define BOLD_WHITE BOLD_SIMPLE_COLOR(37)


#define RESET "\e[0m"

#endif
